---
production:
  multiproxy: true
  port: 80
  logger: 'info'
  AUTH0_CLIENT_ID: 'A47u28ujCjIY2sojBP2JZ3kRkMFykNzy'
  AUTH0_SECRET: 'LvR-XUCEcDYW1KaE_2wRE2fLR6eqBPVJ45akJs4yyYdmXdrIosndsmV4enkzXC94'
  AUTH0_DOMAIN: 'isagroup.eu.auth0.com'
  
development:
  multiproxy: true
  port: 8888
  logger: 'debug'
  AUTH0_CLIENT_ID: 'A47u28ujCjIY2sojBP2JZ3kRkMFykNzy'
  AUTH0_SECRET: 'LvR-XUCEcDYW1KaE_2wRE2fLR6eqBPVJ45akJs4yyYdmXdrIosndsmV4enkzXC94'
  AUTH0_DOMAIN: 'isagroup.eu.auth0.com'
